the form can add data to the database
FACN1/nazareth-events pull request #76
Opened 2017-05-29 13:14 UTC by HilbertSpitzer

#67

2017-05-30 08:20 UTC, mattlub requested changes

2017-05-30 08:20 UTC, mattlub commented on src/server.js
> +  // get the data from the request
this route should require authentication! I just remembered

2017-05-30 11:17 UTC, mattlub approved these changes

2017-05-30 11:17 UTC, mattlub commented
fix the conflict but it's 👍

2017-05-30 11:17 UTC, mattlub commented
habibi

2017-05-30 11:41 UTC, esraajb commented
@HilbertSpitzer what if not all the fields are filled? you can end up with undefined variables

2017-05-31 08:46 UTC, HilbertSpitzer commented
You've got 15 minutes tough guy! Can you manage?

2017-05-31 09:05 UTC, esraajb commented
well done joudy 👍

2017-05-31 09:05 UTC, merged